[
  {
    surat_name: "Al-Fatihah",
    surat_english_terjemahan: "The Opening",
    revelation_type: "Meccan",
    count_ayat: 7,
    surat_text: " الفاتحة",
    surat_golongan: "Makkiyyah",
    surat_terjemahan: "Pembukaan",
    id: 1,
    surat_text_full: "سُورَةُ ٱلْفَاتِحَةِ",
    surat_english_name: "Al-Faatiha",
  },
  {
    surat_golongan: "Madaniyyah",
    surat_terjemahan: "Sapi",
    count_ayat: 286,
    surat_text_full: "سُورَةُ البَقَرَةِ",
    surat_english_terjemahan: "The Cow",
    surat_english_name: "Al-Baqara",
    surat_name: "Al-Baqarah",
    revelation_type: "Medinan",
    id: 2,
    surat_text: " البقرة",
  },
  {
    surat_english_terjemahan: "The Family of Imraan",
    surat_terjemahan: "Keluarga Imran",
    revelation_type: "Medinan",
    id: 3,
    surat_english_name: "Aal-i-Imraan",
    surat_name: "Ali 'Imran",
    surat_text_full: "سُورَةُ آلِ عِمۡرَانَ",
    count_ayat: 200,
    surat_text: " اٰل عمران",
    surat_golongan: "Madaniyyah",
  },
  {
    id: 4,
    surat_golongan: "Madaniyyah",
    surat_text_full: "سُورَةُ النِّسَاءِ",
    revelation_type: "Medinan",
    surat_text: " النساۤء",
    surat_english_terjemahan: "The Women",
    surat_terjemahan: "Wanita",
    surat_english_name: "An-Nisaa",
    count_ayat: 176,
    surat_name: "An-Nisa'",
  },
  {
    surat_text_full: "سُورَةُ المَائـِدَةِ",
    surat_english_name: "Al-Maaida",
    count_ayat: 120,
    surat_english_terjemahan: "The Table",
    surat_terjemahan: "Hidangan",
    surat_golongan: "Madaniyyah",
    surat_name: "Al-Ma'idah",
    id: 5,
    surat_text: " الماۤئدة",
    revelation_type: "Medinan",
  },
  {
    surat_english_name: "Al-An'aam",
    revelation_type: "Meccan",
    surat_english_terjemahan: "The Cattle",
    count_ayat: 165,
    surat_golongan: "Makkiyyah",
    surat_text_full: "سُورَةُ الأَنۡعَامِ",
    surat_name: "Al-An'am",
    surat_terjemahan: "Binatang Ternak",
    surat_text: " الانعام",
    id: 6,
  },
  {
    revelation_type: "Meccan",
    surat_golongan: "Makkiyyah",
    surat_english_name: "Al-A'raaf",
    surat_name: "Al-A'raf",
    id: 7,
    surat_text_full: "سُورَةُ الأَعۡرَافِ",
    count_ayat: 206,
    surat_english_terjemahan: "The Heights",
    surat_terjemahan: "Tempat Tertinggi",
    surat_text: " الاعراف",
  },
  {
    surat_english_terjemahan: "The Spoils of War",
    id: 8,
    surat_golongan: "Madaniyyah",
    surat_text: " الانفال",
    surat_name: "Al-Anfal",
    surat_text_full: "سُورَةُ الأَنفَالِ",
    surat_english_name: "Al-Anfaal",
    revelation_type: "Medinan",
    surat_terjemahan: "Rampasan Perang",
    count_ayat: 75,
  },
  {
    surat_english_terjemahan: "The Repentance",
    surat_terjemahan: "Pengampunan",
    surat_text: " التوبة",
    revelation_type: "Medinan",
    surat_text_full: "سُورَةُ التَّوۡبَةِ",
    surat_name: "At-Taubah",
    id: 9,
    count_ayat: 129,
    surat_english_name: "At-Tawba",
    surat_golongan: "Madaniyyah",
  },
  {
    count_ayat: 109,
    surat_text_full: "سُورَةُ يُونُسَ",
    surat_name: "Yunus",
    surat_text: " يونس",
    surat_golongan: "Makkiyyah",
    surat_english_terjemahan: "Jonas",
    surat_english_name: "Yunus",
    id: 10,
    revelation_type: "Meccan",
    surat_terjemahan: "Yunus",
  },
  {
    surat_terjemahan: "Hud",
    surat_english_terjemahan: "Hud",
    surat_text: " هود",
    surat_english_name: "Hud",
    surat_text_full: "سُورَةُ هُودٍ",
    surat_golongan: "Makkiyyah",
    revelation_type: "Meccan",
    id: 11,
    surat_name: "Hud",
    count_ayat: 123,
  },
  {
    surat_text: " يوسف",
    revelation_type: "Meccan",
    surat_english_name: "Yusuf",
    surat_golongan: "Makkiyyah",
    surat_terjemahan: "Yusuf",
    surat_name: "Yusuf",
    id: 12,
    surat_text_full: "سُورَةُ يُوسُفَ",
    surat_english_terjemahan: "Joseph",
    count_ayat: 111,
  },
  {
    surat_text_full: "سُورَةُ الرَّعۡدِ",
    surat_golongan: "Madaniyyah",
    surat_english_name: "Ar-Ra'd",
    id: 13,
    surat_name: "Ar-Ra'd",
    count_ayat: 43,
    surat_terjemahan: "Guruh",
    surat_text: " الرّعد",
    surat_english_terjemahan: "The Thunder",
    revelation_type: "Medinan",
  },
  {
    surat_terjemahan: "Ibrahim",
    surat_english_terjemahan: "Abraham",
    surat_text: " ابرٰهيم",
    surat_text_full: "سُورَةُ إِبۡرَاهِيمَ",
    surat_name: "Ibrahim",
    count_ayat: 52,
    surat_english_name: "Ibrahim",
    surat_golongan: "Makkiyyah",
    revelation_type: "Meccan",
    id: 14,
  },
  {
    id: 15,
    surat_terjemahan: "Hijr",
    surat_golongan: "Makkiyyah",
    surat_english_name: "Al-Hijr",
    surat_english_terjemahan: "The Rock",
    count_ayat: 99,
    surat_name: "Al-Hijr",
    surat_text: " الحجر",
    revelation_type: "Meccan",
    surat_text_full: "سُورَةُ الحِجۡرِ",
  },
  {
    surat_english_terjemahan: "The Bee",
    surat_text_full: "سُورَةُ النَّحۡلِ",
    surat_terjemahan: "Lebah",
    surat_english_name: "An-Nahl",
    id: 16,
    surat_golongan: "Makkiyyah",
    count_ayat: 128,
    surat_name: "An-Nahl",
    surat_text: " النحل",
    revelation_type: "Meccan",
  },
  {
    surat_name: "Al-Isra'",
    count_ayat: 111,
    surat_english_name: "Al-Israa",
    surat_text: " الاسراۤء",
    surat_english_terjemahan: "The Night Journey",
    revelation_type: "Meccan",
    surat_golongan: "Makkiyyah",
    surat_text_full: "سُورَةُ الإِسۡرَاءِ",
    id: 17,
    surat_terjemahan: "Memperjalankan Malam Hari",
  },
  {
    surat_text_full: "سُورَةُ الكَهۡفِ",
    surat_english_terjemahan: "The Cave",
    revelation_type: "Meccan",
    surat_terjemahan: "Goa",
    id: 18,
    surat_name: "Al-Kahf",
    surat_golongan: "Makkiyyah",
    surat_text: " الكهف",
    surat_english_name: "Al-Kahf",
    count_ayat: 110,
  },
  {
    surat_text_full: "سُورَةُ مَرۡيَمَ",
    count_ayat: 98,
    surat_golongan: "Makkiyyah",
    surat_english_name: "Maryam",
    surat_name: "Maryam",
    id: 19,
    revelation_type: "Meccan",
    surat_terjemahan: "Maryam",
    surat_text: " مريم",
    surat_english_terjemahan: "Mary",
  },
  {
    id: 20,
    surat_golongan: "Makkiyyah",
    surat_terjemahan: "Taha",
    surat_text: " طٰهٰ",
    surat_english_name: "Taa-Haa",
    surat_english_terjemahan: "Taa-Haa",
    count_ayat: 135,
    revelation_type: "Meccan",
    surat_name: "Taha",
    surat_text_full: "سُورَةُ طه",
  },
  {
    surat_golongan: "Makkiyyah",
    surat_terjemahan: "Para Nabi",
    id: 21,
    surat_english_name: "Al-Anbiyaa",
    surat_english_terjemahan: "The Prophets",
    surat_text_full: "سُورَةُ الأَنبِيَاءِ",
    count_ayat: 112,
    surat_name: "Al-Anbiya'",
    revelation_type: "Meccan",
    surat_text: " الانبياۤء",
  },
  {
    revelation_type: "Medinan",
    surat_text_full: "سُورَةُ الحَجِّ",
    surat_english_terjemahan: "The Pilgrimage",
    count_ayat: 78,
    surat_text: " الحج",
    surat_golongan: "Madaniyyah",
    surat_terjemahan: "Haji",
    id: 22,
    surat_name: "Al-Hajj",
    surat_english_name: "Al-Hajj",
  },
  {
    surat_name: "Al-Mu'minun",
    count_ayat: 118,
    surat_text_full: "سُورَةُ المُؤۡمِنُونَ",
    surat_terjemahan: "Orang-Orang Mukmin",
    id: 23,
    revelation_type: "Meccan",
    surat_text: " المؤمنون",
    surat_english_name: "Al-Muminoon",
    surat_english_terjemahan: "The Believers",
    surat_golongan: "Makkiyyah",
  },
  {
    surat_english_terjemahan: "The Light",
    revelation_type: "Medinan",
    surat_text_full: "سُورَةُ النُّورِ",
    surat_name: "An-Nur",
    count_ayat: 64,
    surat_golongan: "Madaniyyah",
    id: 24,
    surat_terjemahan: "Cahaya",
    surat_text: " النّور",
    surat_english_name: "An-Noor",
  },
  {
    surat_name: "Al-Furqan",
    surat_english_name: "Al-Furqaan",
    surat_english_terjemahan: "The Criterion",
    surat_terjemahan: "Pembeda",
    count_ayat: 77,
    id: 25,
    revelation_type: "Meccan",
    surat_text_full: "سُورَةُ الفُرۡقَانِ",
    surat_text: " الفرقان",
    surat_golongan: "Makkiyyah",
  },
  {
    count_ayat: 227,
    surat_text_full: "سُورَةُ الشُّعَرَاءِ",
    surat_golongan: "Makkiyyah",
    surat_terjemahan: "Para Penyair",
    surat_text: " الشعراۤء",
    id: 26,
    surat_english_name: "Ash-Shu'araa",
    surat_english_terjemahan: "The Poets",
    revelation_type: "Meccan",
    surat_name: "Asy-Syu'ara'",
  },
  {
    id: 27,
    surat_name: "An-Naml",
    revelation_type: "Meccan",
    surat_golongan: "Makkiyyah",
    surat_text_full: "سُورَةُ النَّمۡلِ",
    surat_text: " النمل",
    surat_english_name: "An-Naml",
    surat_terjemahan: "Semut-semut",
    count_ayat: 93,
    surat_english_terjemahan: "The Ant",
  },
  {
    surat_english_name: "Al-Qasas",
    surat_text: " القصص",
    surat_text_full: "سُورَةُ القَصَصِ",
    id: 28,
    surat_terjemahan: "Kisah-Kisah",
    surat_english_terjemahan: "The Stories",
    count_ayat: 88,
    surat_name: "Al-Qasas",
    revelation_type: "Meccan",
    surat_golongan: "Makkiyyah",
  },
  {
    surat_text_full: "سُورَةُ العَنكَبُوتِ",
    revelation_type: "Meccan",
    surat_text: " العنكبوت",
    surat_english_name: "Al-Ankaboot",
    count_ayat: 69,
    surat_name: "Al-'Ankabut",
    surat_english_terjemahan: "The Spider",
    surat_golongan: "Makkiyyah",
    id: 29,
    surat_terjemahan: "Laba-Laba",
  },
  {
    surat_english_name: "Ar-Room",
    revelation_type: "Meccan",
    surat_golongan: "Makkiyyah",
    surat_text_full: "سُورَةُ الرُّومِ",
    surat_text: " الرّوم",
    surat_terjemahan: "Romawi",
    id: 30,
    surat_english_terjemahan: "The Romans",
    count_ayat: 60,
    surat_name: "Ar-Rum",
  },
  {
    surat_text_full: "سُورَةُ لُقۡمَانَ",
    surat_name: "Luqman",
    surat_english_terjemahan: "Luqman",
    surat_golongan: "Makkiyyah",
    id: 31,
    count_ayat: 34,
    surat_text: " لقمٰن",
    revelation_type: "Meccan",
    surat_terjemahan: "Luqman",
    surat_english_name: "Luqman",
  },
  {
    id: 32,
    surat_terjemahan: "Sajdah",
    surat_text_full: "سُورَةُ السَّجۡدَةِ",
    revelation_type: "Meccan",
    surat_text: " السّجدة",
    surat_golongan: "Makkiyyah",
    count_ayat: 30,
    surat_name: "As-Sajdah",
    surat_english_terjemahan: "The Prostration",
    surat_english_name: "As-Sajda",
  },
  {
    surat_golongan: "Madaniyyah",
    count_ayat: 73,
    surat_english_name: "Al-Ahzaab",
    surat_name: "Al-Ahzab",
    surat_text: " الاحزاب",
    surat_english_terjemahan: "The Clans",
    surat_terjemahan: "Golongan Yang Bersekutu",
    id: 33,
    surat_text_full: "سُورَةُ الأَحۡزَابِ",
    revelation_type: "Medinan",
  },
  {
    surat_text: " سبأ",
    surat_text_full: "سُورَةُ سَبَإٍ",
    count_ayat: 54,
    surat_name: "Saba'",
    surat_golongan: "Makkiyyah",
    surat_english_terjemahan: "Sheba",
    surat_terjemahan: "Saba'",
    id: 34,
    surat_english_name: "Saba",
    revelation_type: "Meccan",
  },
  {
    count_ayat: 45,
    surat_terjemahan: "Maha Pencipta",
    surat_english_name: "Faatir",
    id: 35,
    surat_name: "Fatir",
    surat_text: " فاطر",
    surat_golongan: "Makkiyyah",
    surat_english_terjemahan: "The Originator",
    revelation_type: "Meccan",
    surat_text_full: "سُورَةُ فَاطِرٍ",
  },
  {
    surat_text: " يٰسۤ",
    count_ayat: 83,
    surat_terjemahan: "Yasin",
    surat_golongan: "Makkiyyah",
    surat_name: "Yasin",
    surat_english_terjemahan: "Yaseen",
    id: 36,
    revelation_type: "Meccan",
    surat_text_full: "سُورَةُ يسٓ",
    surat_english_name: "Yaseen",
  },
  {
    surat_golongan: "Makkiyyah",
    surat_text: " الصّٰۤفّٰت",
    surat_english_name: "As-Saaffaat",
    surat_english_terjemahan: "Those drawn up in Ranks",
    surat_text_full: "سُورَةُ الصَّافَّاتِ",
    surat_name: "As-Saffat",
    count_ayat: 182,
    surat_terjemahan: "Barisan-Barisan",
    revelation_type: "Meccan",
    id: 37,
  },
  {
    surat_text: " ص",
    surat_text_full: "سُورَةُ صٓ",
    surat_name: "Sad",
    count_ayat: 88,
    surat_english_terjemahan: "The letter Saad",
    revelation_type: "Meccan",
    surat_terjemahan: "Sad",
    id: 38,
    surat_golongan: "Makkiyyah",
    surat_english_name: "Saad",
  },
  {
    surat_terjemahan: "Rombongan",
    surat_english_name: "Az-Zumar",
    count_ayat: 75,
    surat_text: " الزمر",
    surat_name: "Az-Zumar",
    surat_text_full: "سُورَةُ الزُّمَرِ",
    revelation_type: "Meccan",
    id: 39,
    surat_english_terjemahan: "The Groups",
    surat_golongan: "Makkiyyah",
  },
  {
    surat_english_name: "Ghafir",
    surat_text: " غافر",
    surat_english_terjemahan: "The Forgiver",
    surat_terjemahan: "Maha Pengampun",
    count_ayat: 85,
    revelation_type: "Meccan",
    surat_name: "Gafir",
    surat_golongan: "Makkiyyah",
    surat_text_full: "سُورَةُ غَافِرٍ",
    id: 40,
  },
  {
    surat_terjemahan: "Yang Dijelaskan",
    count_ayat: 54,
    surat_name: "Fussilat",
    surat_english_terjemahan: "Explained in detail",
    surat_text: " فصّلت",
    surat_text_full: "سُورَةُ فُصِّلَتۡ",
    revelation_type: "Meccan",
    surat_golongan: "Makkiyyah",
    id: 41,
    surat_english_name: "Fussilat",
  },
  {
    surat_golongan: "Makkiyyah",
    surat_name: "Asy-Syura",
    revelation_type: "Meccan",
    surat_english_name: "Ash-Shura",
    surat_terjemahan: "Musyawarah",
    surat_text: " الشورى",
    id: 42,
    surat_english_terjemahan: "Consultation",
    surat_text_full: "سُورَةُ الشُّورَىٰ",
    count_ayat: 53,
  },
  {
    count_ayat: 89,
    surat_terjemahan: "Perhiasan",
    revelation_type: "Meccan",
    surat_text_full: "سُورَةُ الزُّخۡرُفِ",
    surat_english_terjemahan: "Ornaments of gold",
    id: 43,
    surat_golongan: "Makkiyyah",
    surat_name: "Az-Zukhruf",
    surat_text: " الزخرف",
    surat_english_name: "Az-Zukhruf",
  },
  {
    surat_text_full: "سُورَةُ الدُّخَانِ",
    surat_terjemahan: "Kabut",
    count_ayat: 59,
    surat_text: " الدخان",
    surat_english_name: "Ad-Dukhaan",
    id: 44,
    surat_english_terjemahan: "The Smoke",
    surat_golongan: "Makkiyyah",
    surat_name: "Ad-Dukhan",
    revelation_type: "Meccan",
  },
  {
    id: 45,
    surat_text_full: "سُورَةُ الجَاثِيَةِ",
    surat_golongan: "Makkiyyah",
    surat_terjemahan: "Berlutut",
    count_ayat: 37,
    surat_text: " الجاثية",
    surat_name: "Al-Jasiyah",
    surat_english_terjemahan: "Crouching",
    revelation_type: "Meccan",
    surat_english_name: "Al-Jaathiya",
  },
  {
    surat_english_name: "Al-Ahqaf",
    id: 46,
    surat_golongan: "Makkiyyah",
    surat_text_full: "سُورَةُ الأَحۡقَافِ",
    surat_english_terjemahan: "The Dunes",
    revelation_type: "Meccan",
    surat_text: " الاحقاف",
    surat_terjemahan: "Bukit Pasir",
    count_ayat: 35,
    surat_name: "Al-Ahqaf",
  },
  {
    surat_english_name: "Muhammad",
    surat_text: " محمّد",
    revelation_type: "Medinan",
    count_ayat: 38,
    surat_name: "Muhammad",
    surat_terjemahan: "Muhammad",
    id: 47,
    surat_golongan: "Madaniyyah",
    surat_text_full: "سُورَةُ مُحَمَّدٍ",
    surat_english_terjemahan: "Muhammad",
  },
  {
    surat_text_full: "سُورَةُ الفَتۡحِ",
    id: 48,
    surat_golongan: "Madaniyyah",
    surat_english_name: "Al-Fath",
    surat_name: "Al-Fath",
    revelation_type: "Medinan",
    surat_english_terjemahan: "The Victory",
    count_ayat: 29,
    surat_terjemahan: "Kemenangan",
    surat_text: " الفتح",
  },
  {
    surat_english_terjemahan: "The Inner Apartments",
    surat_golongan: "Madaniyyah",
    id: 49,
    surat_english_name: "Al-Hujuraat",
    surat_name: "Al-Hujurat",
    count_ayat: 18,
    revelation_type: "Medinan",
    surat_text: " الحجرٰت",
    surat_text_full: "سُورَةُ الحُجُرَاتِ",
    surat_terjemahan: "Kamar-Kamar",
  },
  {
    surat_text: " ق",
    id: 50,
    surat_terjemahan: "Qaf",
    count_ayat: 45,
    surat_english_terjemahan: "The letter Qaaf",
    surat_golongan: "Makkiyyah",
    surat_name: "Qaf",
    surat_text_full: "سُورَةُ قٓ",
    revelation_type: "Meccan",
    surat_english_name: "Qaaf",
  },
  {
    surat_golongan: "Makkiyyah",
    surat_text: " الذّٰريٰت",
    surat_terjemahan: "Angin yang Menerbangkan",
    surat_english_name: "Adh-Dhaariyat",
    revelation_type: "Meccan",
    id: 51,
    surat_name: "Az-Zariyat",
    surat_english_terjemahan: "The Winnowing Winds",
    count_ayat: 60,
    surat_text_full: "سُورَةُ الذَّارِيَاتِ",
  },
  {
    id: 52,
    surat_golongan: "Makkiyyah",
    revelation_type: "Meccan",
    surat_terjemahan: "Bukit Tursina",
    surat_text_full: "سُورَةُ الطُّورِ",
    surat_english_name: "At-Tur",
    surat_name: "At-Tur",
    count_ayat: 49,
    surat_english_terjemahan: "The Mount",
    surat_text: " الطور",
  },
  {
    surat_text: " النجم",
    revelation_type: "Meccan",
    surat_terjemahan: "Bintang",
    surat_text_full: "سُورَةُ النَّجۡمِ",
    id: 53,
    surat_name: "An-Najm",
    surat_english_terjemahan: "The Star",
    surat_golongan: "Makkiyyah",
    surat_english_name: "An-Najm",
    count_ayat: 62,
  },
  {
    surat_golongan: "Makkiyyah",
    surat_terjemahan: "Bulan",
    surat_english_terjemahan: "The Moon",
    surat_text: " القمر",
    revelation_type: "Meccan",
    surat_name: "Al-Qamar",
    surat_english_name: "Al-Qamar",
    surat_text_full: "سُورَةُ القَمَرِ",
    id: 54,
    count_ayat: 55,
  },
  {
    surat_text_full: "سُورَةُ الرَّحۡمَٰن",
    surat_terjemahan: "Maha Pengasih",
    surat_golongan: "Madaniyyah",
    count_ayat: 78,
    surat_text: " الرحمن",
    surat_english_name: "Ar-Rahmaan",
    surat_name: "Ar-Rahman",
    id: 55,
    surat_english_terjemahan: "The Beneficent",
    revelation_type: "Medinan",
  },
  {
    count_ayat: 96,
    surat_name: "Al-Waqi'ah",
    surat_terjemahan: "Hari Kiamat",
    id: 56,
    surat_golongan: "Makkiyyah",
    surat_text_full: "سُورَةُ الوَاقِعَةِ",
    surat_english_terjemahan: "The Inevitable",
    revelation_type: "Meccan",
    surat_text: " الواقعة",
    surat_english_name: "Al-Waaqia",
  },
  {
    surat_text: " الحديد",
    surat_english_terjemahan: "The Iron",
    surat_text_full: "سُورَةُ الحَدِيدِ",
    revelation_type: "Medinan",
    id: 57,
    count_ayat: 29,
    surat_golongan: "Madaniyyah",
    surat_terjemahan: "Besi",
    surat_english_name: "Al-Hadid",
    surat_name: "Al-Hadid",
  },
  {
    surat_golongan: "Madaniyyah",
    surat_english_name: "Al-Mujaadila",
    id: 58,
    surat_terjemahan: "Gugatan",
    surat_text: " المجادلة",
    surat_text_full: "سُورَةُ المُجَادلَةِ",
    count_ayat: 22,
    revelation_type: "Medinan",
    surat_english_terjemahan: "The Pleading Woman",
    surat_name: "Al-Mujadalah",
  },
  {
    surat_text_full: "سُورَةُ الحَشۡرِ",
    surat_name: "Al-Hasyr",
    count_ayat: 24,
    surat_english_terjemahan: "The Exile",
    surat_terjemahan: "Pengusiran",
    id: 59,
    revelation_type: "Medinan",
    surat_text: " الحشر",
    surat_english_name: "Al-Hashr",
    surat_golongan: "Madaniyyah",
  },
  {
    surat_golongan: "Madaniyyah",
    surat_text_full: "سُورَةُ المُمۡتَحنَةِ",
    surat_english_terjemahan: "She that is to be examined",
    revelation_type: "Medinan",
    surat_text: " الممتحنة",
    surat_terjemahan: "Wanita Yang Diuji",
    id: 60,
    surat_name: "Al-Mumtahanah",
    surat_english_name: "Al-Mumtahana",
    count_ayat: 13,
  },
  {
    id: 61,
    count_ayat: 14,
    surat_terjemahan: "Barisan",
    surat_golongan: "Madaniyyah",
    surat_english_terjemahan: "The Ranks",
    surat_english_name: "As-Saff",
    surat_name: "As-Saff",
    surat_text: " الصّفّ",
    surat_text_full: "سُورَةُ الصَّفِّ",
    revelation_type: "Medinan",
  },
  {
    surat_text: " الجمعة",
    surat_golongan: "Madaniyyah",
    count_ayat: 11,
    id: 62,
    surat_name: "Al-Jumu'ah",
    surat_english_name: "Al-Jumu'a",
    revelation_type: "Medinan",
    surat_terjemahan: "Jumat",
    surat_english_terjemahan: "Friday",
    surat_text_full: "سُورَةُ الجُمُعَةِ",
  },
  {
    surat_text: " المنٰفقون",
    id: 63,
    revelation_type: "Medinan",
    surat_text_full: "سُورَةُ المُنَافِقُونَ",
    surat_terjemahan: "Orang-Orang Munafik",
    surat_english_terjemahan: "The Hypocrites",
    surat_golongan: "Madaniyyah",
    count_ayat: 11,
    surat_name: "Al-Munafiqun",
    surat_english_name: "Al-Munaafiqoon",
  },
  {
    surat_terjemahan: "Pengungkapan Kesalahan",
    surat_text: " التغابن",
    surat_english_name: "At-Taghaabun",
    surat_text_full: "سُورَةُ التَّغَابُنِ",
    count_ayat: 18,
    surat_golongan: "Madaniyyah",
    surat_english_terjemahan: "Mutual Disillusion",
    revelation_type: "Medinan",
    id: 64,
    surat_name: "At-Tagabun",
  },
  {
    surat_text: " الطلاق",
    id: 65,
    surat_text_full: "سُورَةُ الطَّلَاقِ",
    surat_name: "At-Talaq",
    surat_golongan: "Madaniyyah",
    surat_english_name: "At-Talaaq",
    surat_english_terjemahan: "Divorce",
    surat_terjemahan: "Talak",
    count_ayat: 12,
    revelation_type: "Medinan",
  },
  {
    surat_text: " التحريم",
    surat_terjemahan: "Pengharaman",
    id: 66,
    surat_english_terjemahan: "The Prohibition",
    revelation_type: "Medinan",
    surat_english_name: "At-Tahrim",
    surat_text_full: "سُورَةُ التَّحۡرِيمِ",
    count_ayat: 12,
    surat_name: "At-Tahrim",
    surat_golongan: "Madaniyyah",
  },
  {
    surat_text_full: "سُورَةُ المُلۡكِ",
    count_ayat: 30,
    surat_english_terjemahan: "The Sovereignty",
    surat_text: " الملك",
    surat_english_name: "Al-Mulk",
    surat_name: "Al-Mulk",
    id: 67,
    revelation_type: "Meccan",
    surat_terjemahan: "Kerajaan",
    surat_golongan: "Makkiyyah",
  },
  {
    id: 68,
    surat_english_terjemahan: "The Pen",
    surat_english_name: "Al-Qalam",
    count_ayat: 52,
    revelation_type: "Meccan",
    surat_golongan: "Makkiyyah",
    surat_terjemahan: "Pena",
    surat_text_full: "سُورَةُ القَلَمِ",
    surat_text: " القلم",
    surat_name: "Al-Qalam",
  },
  {
    count_ayat: 52,
    surat_text: " الحاۤقّة",
    surat_english_name: "Al-Haaqqa",
    surat_name: "Al-Haqqah",
    surat_terjemahan: "Hari Kiamat",
    surat_english_terjemahan: "The Reality",
    revelation_type: "Meccan",
    surat_text_full: "سُورَةُ الحَاقَّةِ",
    surat_golongan: "Makkiyyah",
    id: 69,
  },
  {
    surat_golongan: "Makkiyyah",
    surat_terjemahan: "Tempat Naik",
    surat_text_full: "سُورَةُ المَعَارِجِ",
    revelation_type: "Meccan",
    id: 70,
    surat_english_terjemahan: "The Ascending Stairways",
    surat_english_name: "Al-Ma'aarij",
    count_ayat: 44,
    surat_name: "Al-Ma'arij",
    surat_text: " المعارج",
  },
  {
    surat_golongan: "Makkiyyah",
    surat_english_terjemahan: "Noah",
    surat_english_name: "Nooh",
    surat_terjemahan: "Nuh",
    revelation_type: "Meccan",
    surat_name: "Nuh",
    id: 71,
    count_ayat: 28,
    surat_text: " نوح",
    surat_text_full: "سُورَةُ نُوحٍ",
  },
  {
    id: 72,
    surat_text: " الجن",
    surat_name: "Al-Jinn",
    surat_english_name: "Al-Jinn",
    surat_terjemahan: "Jin",
    count_ayat: 28,
    revelation_type: "Meccan",
    surat_english_terjemahan: "The Jinn",
    surat_golongan: "Makkiyyah",
    surat_text_full: "سُورَةُ الجِنِّ",
  },
  {
    count_ayat: 20,
    surat_text: " المزّمّل",
    surat_text_full: "سُورَةُ المُزَّمِّلِ",
    surat_english_name: "Al-Muzzammil",
    surat_name: "Al-Muzzammil",
    id: 73,
    surat_golongan: "Makkiyyah",
    surat_english_terjemahan: "The Enshrouded One",
    revelation_type: "Meccan",
    surat_terjemahan: "Orang Yang Berselimut",
  },
  {
    id: 74,
    surat_text_full: "سُورَةُ المُدَّثِّرِ",
    surat_terjemahan: "Orang Yang Berkemul",
    count_ayat: 56,
    surat_name: "Al-Muddassir",
    surat_english_name: "Al-Muddaththir",
    surat_golongan: "Makkiyyah",
    surat_english_terjemahan: "The Cloaked One",
    surat_text: " المدّثّر",
    revelation_type: "Meccan",
  },
  {
    count_ayat: 40,
    revelation_type: "Meccan",
    surat_english_terjemahan: "The Resurrection",
    surat_name: "Al-Qiyamah",
    surat_text_full: "سُورَةُ القِيَامَةِ",
    id: 75,
    surat_text: " القيٰمة",
    surat_terjemahan: "Hari Kiamat",
    surat_english_name: "Al-Qiyaama",
    surat_golongan: "Makkiyyah",
  },
  {
    surat_name: "Al-Insan",
    count_ayat: 31,
    id: 76,
    surat_terjemahan: "Manusia",
    surat_text_full: "سُورَةُ الإِنسَانِ",
    surat_text: " الانسان",
    surat_english_name: "Al-Insaan",
    revelation_type: "Medinan",
    surat_english_terjemahan: "Man",
    surat_golongan: "Madaniyyah",
  },
  {
    surat_text_full: "سُورَةُ المُرۡسَلَاتِ",
    count_ayat: 50,
    surat_text: " المرسلٰت",
    surat_terjemahan: "Malaikat Yang Diutus",
    id: 77,
    surat_english_name: "Al-Mursalaat",
    surat_english_terjemahan: "The Emissaries",
    surat_name: "Al-Mursalat",
    revelation_type: "Meccan",
    surat_golongan: "Makkiyyah",
  },
  {
    surat_golongan: "Makkiyyah",
    surat_english_terjemahan: "The Announcement",
    surat_name: "An-Naba'",
    id: 78,
    revelation_type: "Meccan",
    surat_terjemahan: "Berita Besar",
    surat_english_name: "An-Naba",
    count_ayat: 40,
    surat_text_full: "سُورَةُ النَّبَإِ",
    surat_text: " النبأ",
  },
  {
    surat_text: " النّٰزعٰت",
    surat_english_terjemahan: "Those who drag forth",
    count_ayat: 46,
    surat_golongan: "Makkiyyah",
    revelation_type: "Meccan",
    surat_name: "An-Nazi'at",
    id: 79,
    surat_text_full: "سُورَةُ النَّازِعَاتِ",
    surat_terjemahan: "Malaikat Yang Mencabut",
    surat_english_name: "An-Naazi'aat",
  },
  {
    surat_text: " عبس",
    surat_text_full: "سُورَةُ عَبَسَ",
    revelation_type: "Meccan",
    surat_english_terjemahan: "He frowned",
    surat_name: "'Abasa",
    surat_english_name: "Abasa",
    surat_golongan: "Makkiyyah",
    id: 80,
    surat_terjemahan: "Bermuka Masam",
    count_ayat: 42,
  },
  {
    surat_terjemahan: "Penggulungan",
    count_ayat: 29,
    surat_english_terjemahan: "The Overthrowing",
    surat_english_name: "At-Takwir",
    id: 81,
    surat_golongan: "Makkiyyah",
    surat_text_full: "سُورَةُ التَّكۡوِيرِ",
    surat_text: " التكوير",
    revelation_type: "Meccan",
    surat_name: "At-Takwir",
  },
  {
    surat_golongan: "Makkiyyah",
    count_ayat: 19,
    surat_text: " الانفطار",
    id: 82,
    surat_terjemahan: "Terbelah",
    revelation_type: "Meccan",
    surat_english_name: "Al-Infitaar",
    surat_english_terjemahan: "The Cleaving",
    surat_name: "Al-Infitar",
    surat_text_full: "سُورَةُ الانفِطَارِ",
  },
  {
    surat_terjemahan: "Orang-Orang Curang",
    count_ayat: 36,
    id: 83,
    surat_text: " المطفّفين",
    surat_golongan: "Makkiyyah",
    surat_english_name: "Al-Mutaffifin",
    surat_name: "Al-Mutaffifin",
    revelation_type: "Meccan",
    surat_text_full: "سُورَةُ المُطَفِّفِينَ",
    surat_english_terjemahan: "Defrauding",
  },
  {
    surat_text: " الانشقاق",
    count_ayat: 25,
    surat_text_full: "سُورَةُ الانشِقَاقِ",
    id: 84,
    surat_english_terjemahan: "The Splitting Open",
    surat_terjemahan: "Terbelah",
    surat_english_name: "Al-Inshiqaaq",
    surat_name: "Al-Insyiqaq",
    revelation_type: "Meccan",
    surat_golongan: "Makkiyyah",
  },
  {
    id: 85,
    surat_english_terjemahan: "The Constellations",
    count_ayat: 22,
    surat_golongan: "Makkiyyah",
    surat_english_name: "Al-Burooj",
    surat_terjemahan: "Gugusan Bintang",
    revelation_type: "Meccan",
    surat_text: " البروج",
    surat_name: "Al-Buruj",
    surat_text_full: "سُورَةُ البُرُوجِ",
  },
  {
    count_ayat: 17,
    revelation_type: "Meccan",
    surat_english_name: "At-Taariq",
    surat_name: "At-Tariq",
    surat_golongan: "Makkiyyah",
    surat_text_full: "سُورَةُ الطَّارِقِ",
    id: 86,
    surat_text: " الطارق",
    surat_terjemahan: "Yang Datang Di Malam Hari",
    surat_english_terjemahan: "The Morning Star",
  },
  {
    surat_text: " الاعلى",
    surat_text_full: "سُورَةُ الأَعۡلَىٰ",
    revelation_type: "Meccan",
    id: 87,
    surat_english_terjemahan: "The Most High",
    surat_name: "Al-A'la",
    count_ayat: 19,
    surat_terjemahan: "Maha Tinggi",
    surat_english_name: "Al-A'laa",
    surat_golongan: "Makkiyyah",
  },
  {
    surat_text_full: "سُورَةُ الغَاشِيَةِ",
    surat_text: " الغاشية",
    revelation_type: "Meccan",
    count_ayat: 26,
    id: 88,
    surat_english_terjemahan: "The Overwhelming",
    surat_english_name: "Al-Ghaashiya",
    surat_name: "Al-Gasyiyah",
    surat_terjemahan: "Hari Kiamat",
    surat_golongan: "Makkiyyah",
  },
  {
    surat_text_full: "سُورَةُ الفَجۡرِ",
    surat_terjemahan: "Fajar",
    surat_name: "Al-Fajr",
    surat_english_name: "Al-Fajr",
    count_ayat: 30,
    surat_golongan: "Makkiyyah",
    surat_text: " الفجر",
    surat_english_terjemahan: "The Dawn",
    id: 89,
    revelation_type: "Meccan",
  },
  {
    surat_text: " البلد",
    surat_text_full: "سُورَةُ البَلَدِ",
    surat_terjemahan: "Negeri",
    revelation_type: "Meccan",
    id: 90,
    surat_english_name: "Al-Balad",
    surat_name: "Al-Balad",
    surat_english_terjemahan: "The City",
    surat_golongan: "Makkiyyah",
    count_ayat: 20,
  },
  {
    surat_golongan: "Makkiyyah",
    revelation_type: "Meccan",
    surat_english_terjemahan: "The Sun",
    surat_terjemahan: "Matahari",
    surat_english_name: "Ash-Shams",
    surat_name: "Asy-Syams",
    surat_text: " الشمس",
    surat_text_full: "سُورَةُ الشَّمۡسِ",
    id: 91,
    count_ayat: 15,
  },
  {
    count_ayat: 21,
    surat_text: " الّيل",
    id: 92,
    surat_english_terjemahan: "The Night",
    revelation_type: "Meccan",
    surat_golongan: "Makkiyyah",
    surat_terjemahan: "Malam",
    surat_text_full: "سُورَةُ اللَّيۡلِ",
    surat_name: "Al-Lail",
    surat_english_name: "Al-Lail",
  },
  {
    surat_english_terjemahan: "The Morning Hours",
    surat_golongan: "Makkiyyah",
    surat_name: "Ad-Duha",
    surat_english_name: "Ad-Dhuhaa",
    surat_terjemahan: "Duha",
    surat_text: " الضحى",
    surat_text_full: "سُورَةُ الضُّحَىٰ",
    revelation_type: "Meccan",
    id: 93,
    count_ayat: 11,
  },
  {
    surat_english_name: "Ash-Sharh",
    surat_name: "Asy-Syarh",
    surat_text_full: "سُورَةُ الشَّرۡحِ",
    surat_golongan: "Makkiyyah",
    id: 94,
    revelation_type: "Meccan",
    surat_text: " الشرح",
    surat_english_terjemahan: "The Consolation",
    count_ayat: 8,
    surat_terjemahan: "Lapang",
  },
  {
    surat_golongan: "Makkiyyah",
    surat_text_full: "سُورَةُ التِّينِ",
    surat_terjemahan: "Buah Tin",
    surat_text: " التين",
    surat_english_name: "At-Tin",
    surat_name: "At-Tin",
    id: 95,
    revelation_type: "Meccan",
    surat_english_terjemahan: "The Fig",
    count_ayat: 8,
  },
  {
    surat_name: "Al-'Alaq",
    surat_terjemahan: "Segumpal Darah",
    surat_english_terjemahan: "The Clot",
    revelation_type: "Meccan",
    surat_golongan: "Makkiyyah",
    id: 96,
    surat_text: " العلق",
    surat_english_name: "Al-Alaq",
    surat_text_full: "سُورَةُ العَلَقِ",
    count_ayat: 19,
  },
  {
    count_ayat: 5,
    id: 97,
    surat_name: "Al-Qadr",
    surat_english_name: "Al-Qadr",
    revelation_type: "Meccan",
    surat_text: " القدر",
    surat_text_full: "سُورَةُ القَدۡرِ",
    surat_english_terjemahan: "The Power, Fate",
    surat_golongan: "Makkiyyah",
    surat_terjemahan: "Kemuliaan",
  },
  {
    surat_golongan: "Madaniyyah",
    surat_terjemahan: "Bukti Nyata",
    surat_name: "Al-Bayyinah",
    id: 98,
    surat_english_terjemahan: "The Evidence",
    surat_text: " البيّنة",
    surat_english_name: "Al-Bayyina",
    surat_text_full: "سُورَةُ البَيِّنَةِ",
    revelation_type: "Medinan",
    count_ayat: 8,
  },
  {
    count_ayat: 8,
    surat_text_full: "سُورَةُ الزَّلۡزَلَةِ",
    surat_terjemahan: "Guncangan",
    surat_golongan: "Madaniyyah",
    id: 99,
    surat_english_name: "Az-Zalzala",
    surat_text: " الزلزلة",
    surat_english_terjemahan: "The Earthquake",
    surat_name: "Az-Zalzalah",
    revelation_type: "Medinan",
  },
  {
    surat_english_terjemahan: "The Chargers",
    surat_text_full: "سُورَةُ العَادِيَاتِ",
    surat_english_name: "Al-Aadiyaat",
    count_ayat: 11,
    id: 100,
    surat_golongan: "Makkiyyah",
    surat_text: " العٰديٰت",
    revelation_type: "Meccan",
    surat_terjemahan: "Kuda Yang Berlari Kencang",
    surat_name: "Al-'Adiyat",
  },
  {
    surat_english_name: "Al-Qaari'a",
    surat_text_full: "سُورَةُ القَارِعَةِ",
    revelation_type: "Meccan",
    id: 101,
    surat_golongan: "Makkiyyah",
    surat_text: " القارعة",
    surat_name: "Al-Qari'ah",
    surat_terjemahan: "Hari Kiamat",
    surat_english_terjemahan: "The Calamity",
    count_ayat: 11,
  },
  {
    surat_golongan: "Makkiyyah",
    id: 102,
    count_ayat: 8,
    surat_english_name: "At-Takaathur",
    surat_name: "At-Takasur",
    surat_text_full: "سُورَةُ التَّكَاثُرِ",
    surat_english_terjemahan: "Competition",
    surat_terjemahan: "Bermegah-Megahan",
    surat_text: " التكاثر",
    revelation_type: "Meccan",
  },
  {
    surat_name: "Al-'Asr",
    surat_text: " العصر",
    surat_terjemahan: "Asar",
    count_ayat: 3,
    revelation_type: "Meccan",
    surat_english_terjemahan: "The Declining Day, Epoch",
    surat_text_full: "سُورَةُ العَصۡرِ",
    surat_english_name: "Al-Asr",
    surat_golongan: "Makkiyyah",
    id: 103,
  },
  {
    surat_name: "Al-Humazah",
    revelation_type: "Meccan",
    id: 104,
    surat_english_terjemahan: "The Traducer",
    surat_text_full: "سُورَةُ الهُمَزَةِ",
    surat_terjemahan: "Pengumpat",
    surat_text: " الهمزة",
    surat_golongan: "Makkiyyah",
    count_ayat: 9,
    surat_english_name: "Al-Humaza",
  },
  {
    revelation_type: "Meccan",
    id: 105,
    surat_text_full: "سُورَةُ الفِيلِ",
    surat_english_name: "Al-Fil",
    surat_name: "Al-Fil",
    surat_text: " الفيل",
    count_ayat: 5,
    surat_terjemahan: "Gajah",
    surat_english_terjemahan: "The Elephant",
    surat_golongan: "Makkiyyah",
  },
  {
    surat_text: " قريش",
    surat_english_terjemahan: "Quraysh",
    surat_name: "Quraisy",
    revelation_type: "Meccan",
    surat_english_name: "Quraish",
    surat_text_full: "سُورَةُ قُرَيۡشٍ",
    count_ayat: 4,
    surat_terjemahan: "Quraisy",
    surat_golongan: "Makkiyyah",
    id: 106,
  },
  {
    surat_golongan: "Makkiyyah",
    surat_english_name: "Al-Maa'un",
    id: 107,
    count_ayat: 7,
    surat_terjemahan: "Barang Yang Berguna",
    surat_name: "Al-Ma'un",
    surat_text_full: "سُورَةُ المَاعُونِ",
    surat_english_terjemahan: "Almsgiving",
    surat_text: " الماعون",
    revelation_type: "Meccan",
  },
  {
    surat_terjemahan: "Pemberian Yang Banyak",
    surat_english_terjemahan: "Abundance",
    surat_name: "Al-Kausar",
    id: 108,
    surat_english_name: "Al-Kawthar",
    surat_text_full: "سُورَةُ الكَوۡثَرِ",
    surat_golongan: "Makkiyyah",
    surat_text: " الكوثر",
    count_ayat: 3,
    revelation_type: "Meccan",
  },
  {
    count_ayat: 6,
    surat_english_terjemahan: "The Disbelievers",
    surat_english_name: "Al-Kaafiroon",
    surat_text_full: "سُورَةُ الكَافِرُونَ",
    surat_text: " الكٰفرون",
    surat_name: "Al-Kafirun",
    id: 109,
    surat_golongan: "Makkiyyah",
    revelation_type: "Meccan",
    surat_terjemahan: "Orang-Orang kafir",
  },
  {
    revelation_type: "Medinan",
    surat_golongan: "Madaniyyah",
    id: 110,
    surat_terjemahan: "Pertolongan",
    surat_text_full: "سُورَةُ النَّصۡرِ",
    surat_english_terjemahan: "Divine Support",
    surat_english_name: "An-Nasr",
    surat_text: " النصر",
    count_ayat: 3,
    surat_name: "An-Nasr",
  },
  {
    surat_name: "Al-Lahab",
    count_ayat: 5,
    surat_text_full: "سُورَةُ المَسَدِ",
    surat_english_name: "Al-Masad",
    surat_english_terjemahan: "The Palm Fibre",
    surat_terjemahan: "Api Yang Bergejolak",
    id: 111,
    surat_text: " اللهب",
    revelation_type: "Meccan",
    surat_golongan: "Makkiyyah",
  },
  {
    surat_golongan: "Makkiyyah",
    count_ayat: 4,
    surat_name: "Al-Ikhlas",
    surat_text_full: "سُورَةُ الإِخۡلَاصِ",
    revelation_type: "Meccan",
    surat_text: " الاخلاص",
    surat_english_terjemahan: "Sincerity",
    surat_terjemahan: "Ikhlas",
    id: 112,
    surat_english_name: "Al-Ikhlaas",
  },
  {
    id: 113,
    surat_text_full: "سُورَةُ الفَلَقِ",
    surat_english_name: "Al-Falaq",
    surat_golongan: "Makkiyyah",
    surat_text: " الفلق",
    surat_english_terjemahan: "The Dawn",
    surat_terjemahan: "Subuh",
    count_ayat: 5,
    surat_name: "Al-Falaq",
    revelation_type: "Meccan",
  },
  {
    id: 114,
    surat_english_terjemahan: "Mankind",
    surat_terjemahan: "Manusia",
    surat_name: "An-Nas",
    surat_english_name: "An-Naas",
    revelation_type: "Meccan",
    surat_golongan: "Makkiyyah",
    surat_text_full: "سُورَةُ النَّاسِ",
    surat_text: " الناس",
    count_ayat: 6,
  },
];
